apiVersion: v1
kind: Secret
metadata:
    name: openbao-break-glass
    namespace: openbao
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:aNYwmTmd6PvBL7d074rE09TeTS6cqH5dYb0RHshdOkg=,iv:vYOzIXfldDPYpb93RlHOFRgmxmQsJ5XNz4aKdEUXyBs=,tag:8NQEM792lpLk16H/5vrMqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N1R4Sk43WDVJMWhXNSs4
            SWhvdkdrdXhhemt0V291YmdyUFJPei9SZTBJCkRTdmRydUlyWG4zU2NxSDFsclpt
            MXpuQTVMWDJVakVhT1JjRFNwL0xhUk0KLS0tIEJ5M08ySjl2OGU2WWZ0MnB3ZWFz
            L2s1ZHZHYWRUbStmNDhLUnhnblZnaFkKUyFSd4QdbzaHnmxNo3GWF9cqbsRfoyXN
            DB7hMg5UYDKQGgrlb2OdwKh6EEn6AIzcg0BmI+IiJ8boNP9bQXAzPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyt4450vl74xy5nlf585jm53lrxhapqy8rn9tm7w922rnmf6uevsj0llcl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVVpHeFdFVEc1Smp3K2lr
            cnk4S3lMZTBjMk14eFJzM2FoV1I1b2o5U1JvCkdmZGVreEJJNEdVTU1QWHFoVFZV
            RlpiQ01EZy9ESDBLUURnNDIxUkQ5dXcKLS0tIFo2cGRJR09XVkk5SDdEaVdFSjJT
            R2wrSjljNFJUejF5NktGbk5hZjJiZ00K9GSGbU54RZ/Rig6YzPKOCoT2xs7u/Wt/
            vc8DYMlWU6apl/xYU6ZXkl8o4JNpLywr6Yvdn+IMQLjLmTVtvVALzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hwv2gk7peqx7lr7q08pvd3ec5djs3n57mrswf9maexy4puay53msy7395t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T11:47:11Z"
    mac: ENC[AES256_GCM,data:Pj22I9zmWU4dOqS7RFmeqb4eTlt1uPYwevY27Vz5paUtpvyTAeprYTJpkpFltRC8+I2TcNs7u33tAs3UXfi7dn05oDjet0golFaG3gKbn9yhSza78OF4rJuoNHj662x0CS4YeDwNMcWPeCn856iiOhUl5YzPR/T8hghJkb0BlYY=,iv:vHcXeAstO98Tzb5Gy26DqYPoahMszAmVSgaO9PyYZ5A=,tag:xl7sS6dBaozdSXDx2TxyhA==,type:str]
    version: 3.13.3
