apiVersion: v1
kind: Secret
metadata:
    name: openbao-db-credential
    namespace: openbao
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8CDK3w5gxQ==,iv:j8HA6vQwCbn8R1Xa2fILBN0rsBNzt9dxG6TMQXlaT+4=,tag:0jx+XKsQKtI9te6OAy+Dqw==,type:str]
    password: ENC[AES256_GCM,data:9vPXwquJbdMPpFxpWcguCYw1vMsFJAHyJGrvkBhov2A/xzkiv7aHOkITikC2xl7cFZFqd4CtegFnnWD0GN86cg==,iv:nJjtOQ81Jdq0FVM47loXWVbxFiLgefWK7+Inn/XP+og=,tag:6Y9f+nBaFqJkXQ5w1tMdrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQlZ5Q1h3ZCt2alVHV0Zn
            eitNais5L3JiWXppLzByZ044R3p5S0hJY1hRClBZSXZVWk4zLzAxaGNoRnF3ekpq
            NjJtUjBJZjJvRzJPTDFRM0tOR2RINjAKLS0tIE9wRC82eXBtbU1zM3M3VS9JWTd3
            TzBONnpQTS9UYS9hSTgrZTNrdzlLRHMKI8ezQL1sUJ/cnskUpvfEUu/eRFh2vYzX
            LSRCwxp3Ug8GwHIyBAihFqvGYmyXqSqSjsP5f/bCnjsgT/I3TD4q0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyt4450vl74xy5nlf585jm53lrxhapqy8rn9tm7w922rnmf6uevsj0llcl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHdaWnV0V0xwclVucXNk
            SnZkWXUyKzV3T1dwcXh6R2JRMm9YWDRNalQ0CkVUd2VmeTNmTVMvem1KQmxSYmpl
            RTRoWktyZjV0c2t3NTYrbkdtaEd1MDQKLS0tIHIyTjlBekVsU2cyblBmQ2NydTFn
            WDhacFRxN0VZWUlIUk91RWxHRGNDQ1UKMH3/GuZljk9NswH/+MAyLuZMBIe/UJVm
            UEzCptMf6hm4S33J2AupF6WHTQFbiL4HkAnDU6L3kaYOt7/H4WxsZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hwv2gk7peqx7lr7q08pvd3ec5djs3n57mrswf9maexy4puay53msy7395t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:20:01Z"
    mac: ENC[AES256_GCM,data:cA6UE2UdfYIr2BgFb1/EWhrJ5BCJS3DLpf0ntG+/eLfSRIDbLg7F9hj4lboGD0Mb/mE+ckLcxjSn2eZY8HKKamQVmOr1PFqJK9T4pSRnFtkd3qajN2ImqRxYSgtrt6fgprd/c+8s997kN1aYuG9nH2LDBP3BikxDG/VR7ueTZUk=,iv:jH2BFwyg/m1b4BG6RffBmsxqqQVAafeDrGhfLd+cD8k=,tag:AwXqB+O0e8PYWGOjuhY28Q==,type:str]
    version: 3.13.3
