apiVersion: v1
kind: Secret
metadata:
    name: backup-store-credential
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:p88Qp7eOddWeC5czwOAmCMkKwmY=,iv:kJLTJFCGVyYjM2XDQXXuTyOIT/eyKNO8xVTkqLiEkwU=,tag:0shWMIli+zC1VBV4FAzGeQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:53iiPygXScE5Xp+CldRV+P1xW81NV6DHdwCBFNi6noAQYVJwObTJIg==,iv:C5zZK+Dn6E0NEMJTG6EaJBNzhwzjU8Chhcm5+yo4HPg=,tag:Qv8PbhnSyOu2BU/7qK9Twg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMTZKaE5sRVZjUUJCQXJk
            M3pST2czNnpYMVpMMVdiYTNUUGhTVXUzNG5VCmtpY2tnUEs2cWpqNzJNb2tEWnRN
            YkJYYllSTktQY1UzTkVVZ1JhU2g2VkkKLS0tIFRsNmRwQ0Q1YXduYVh6ay9zV0hu
            blJrQlNYZlUxd3JlWVlpZmh5R3JsL00K8fbe7qGSw5GmMRTnYHq7FEL403sEn5o2
            897IDyFvMHfpjEM1nAnCUSwYNSQRcXtD2z1thGP04Dk4oJBDxRtK6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyt4450vl74xy5nlf585jm53lrxhapqy8rn9tm7w922rnmf6uevsj0llcl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM1ltVUhMczdPSGdhaWcr
            OGp4L0RPbk8zOU1YRnVEQUt5TGpHLzNhWDJFClZqR0djbTJBVkNXWStmUXZzeTdW
            ZVJKODhVdVl0YmVpcUIzTEJtenpIa2MKLS0tIHd6SmRRSEVsS29Wck5tWmlycVhB
            R01aM2FtTkFXTUVOVmVXQjIvVGVCNmsKF5+Q6THER2Qhds4PJVF8xBcwPcQHMSpQ
            Oa43HeULInPMK8h+yh6gsUJ1Dx4eGlrjdgXwaxL5Oe8JP6zQaHLSpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hwv2gk7peqx7lr7q08pvd3ec5djs3n57mrswf9maexy4puay53msy7395t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T10:43:28Z"
    mac: ENC[AES256_GCM,data:BgYHuADFBZYeq/bha7cHOk2BpPueQNzaSzZ39NipEfudt/apvqfZkpDi8kd9Ie3LghMwRmS1eDE8ZJGSZaAIEaoKG3ljXlJkLZlus4s/CIHmtJm0vsDvH28iWizHgDpwN0hs3z5E5l8exXnKk2fsRMJnKecMgK5veZCwMGCs0go=,iv:qV8RFcQtlfeYeE/N4GCkIsundR6nzsgOm1Eqs9FgESY=,tag:9L314BYLbc8ca65F+lwrYQ==,type:str]
    version: 3.13.3
