apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backup-store-ca.yaml
  - backup-store-credential.sops.yaml
  - objectstore.yaml
  - openbao-db-credential.sops.yaml
  - cluster.yaml
  - scheduled-backup.yaml
