apiVersion: v1
kind: Secret
metadata:
    name: openbao-db-credential
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:G9iBFz42QQ==,iv:69WJOpSfImolcd28T7Q4Y0TcgYE9SPgTZNYYXbNX2U4=,tag:HCKUZDnbMJlAYx0jT/ePSg==,type:str]
    password: ENC[AES256_GCM,data:dV1fZM8mvY9wJY2iFB3nZO5jlcmCx7ZsqzUYkTTcGeZa4qqLyjzIundMZkm0/7VXcf3bTDIZZo9C+00HCsufAw==,iv:xChDpE9wJXc3zKBIKwKjevI50AQpCfXoGz40/i83NyY=,tag:UbEXH64fY/ljXX0bssN6zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcEFIWjR5MllleTFFT0xD
            d0ZPWkdrVnFkd1FSWUZKcm5QVVNXUnlwRnlzCkpCbHE3LzBFUU41Mm0wNjA5bmVO
            VW5yR25yMWNuZFphL2p4cU94ZUE5MWcKLS0tIFVRblg0VDhVU2hjWFFsSGdlYmtN
            eDFlVmJDKzYxWnExK2YxVWpsY1RqZVkK1ZQEW436DcAIh343fk8X0x3S/Vru7w4/
            azRGyrcXo7QtysAPgQgjPRvw4StNOvMjdXOVtCdzJB+z++xO46rU1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyt4450vl74xy5nlf585jm53lrxhapqy8rn9tm7w922rnmf6uevsj0llcl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNkYxSGtrVlE3MjRlei9Q
            QmJHSk9tQ2tQS1hDcE5LSEFSZ3JHNWM2TDBrCmEwSmpscGNDbnk2MkZmN0dydVFM
            dHEweHJPbExNbFBsZkRaTEZWMzFnaTQKLS0tIEF5MU9ZOHlBZkZrYkxkNE9pajlU
            UEZhSjBsZFZoaGNnL0tvWEYvZUt2N3MKuqpm7LqDDG3TLloaOdPVEJbN3aavL9mU
            lxNWRveha3m55rgIfrTH5cQNWWAk87NE59vJIihnpCZkWbaJU6pnMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hwv2gk7peqx7lr7q08pvd3ec5djs3n57mrswf9maexy4puay53msy7395t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T12:09:40Z"
    mac: ENC[AES256_GCM,data:HHc2HMzQvJTH4/uSlRp1zm6At+Uma59GqdMFwb3XgkaPVi9KhgktLQazd61xbQ5jypk8n+aownfnZ47O3ceBcX5vPCgzWH0qJaUIqgti6IGRe4ZG+ZSg1IaO0ZmirimCahtaeTkgz31zIkUi1znvMLzCFnaUZSmoRvvHzyydJoA=,iv:DQcKZd0ammsaWYvgTTlwk3DFA4Jl0V5VuvWBJyxX7R0=,tag:Vfkza6k+Ke2mAHJdqGbfLQ==,type:str]
    version: 3.13.3
