apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-pull
  namespace: demo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-push
  namespace: demo
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-token-create
  namespace: demo
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
    resourceNames:
      - eso-pull
      - eso-push
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-token-create
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-token-create
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
